#!/bin/bash
R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

LOGS_FOLDER="/var/log/expense"
SCRIPT_NAME=$(echo $0 | cut -d "." -f1)
TIME_STAMP=$(date +%Y-%m-%d-%H-%M-%S)
LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME-$TIME_STAMP.log"

mkdir -p $LOGS_FOLDER

CHECK_ROOT(){
    USER_ID=$(id -u)
    if [ $USER_ID -ne 0 ]
    then
        echo -e "$R please run the script with root user access $N"        | tee -a $LOG_FILE
        exit 1
    fi
}
CHECK_ROOT

echo -e "Script started executing at :$Y $(date) $N"      | tee -a $LOG_FILE

VALIDATE(){
    if [ $1 -ne 0 ]
    then
        echo -e "$2 is $R FAILED.. $N"            | tee -a $LOG_FILE
        exit 1
    else
        echo -e "$2 is $G SUCCESS.. $N"           | tee -a $LOG_FILE
    fi
}

dnf module disable nodejs -y            &>>$$LOG_FILE
VALIDATE $? "Disabling default nodejs"

dnf module enable nodejs:20 -y          &>>$$LOG_FILE
VALIDATE $? "Enabling nodejs:20"

dnf install nodejs -y                  &>>$$LOG_FILE
VALIDATE $? "Installing nodejs"

id expense                             &>>$$LOG_FILE
if [ $? -ne 0 ]
then
    echo -e "expense user is not $Y created.. creating $N"   | tee -a $LOG_FILE
    useradd expense                     &>>$$LOG_FILE
    VALIDATE $? "Creating Expense user"
else
    echo -e "expense user already created.. $G skip creating $N"    | tee -a $LOG_FILE
fi

mkdir -p /app
VALIDATE $? "Creating app directory"

curl -o /tmp/backend.zip https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip  &>>$$LOG_FILE
VALIDATE $? "downloading backend code"

cd /app
rm -rf /app/*
unzip /tmp/backend.zip   &>>$$LOG_FILE
VALIDATE $? "Extracting zip file"

npm install         &>>$$LOG_FILE
VALIDATE $? "Build tool installation"

cp /home/ec2-user/scripting/backend.service /etc/systemd/system/backend.service

dnf install mysql -y      &>>$$LOG_FILE
VALIDATE $? "Installing mysql client"

mysql -h mysql.muntaj.fun -uroot -pExpenseApp@1 < /app/schema/backend.sql
VALIDATE $? "Schema loading"

systemctl daemon-reload       &>>$$LOG_FILE
VALIDATE $? "daemon-reload"

systemctl enable backend       &>>$$LOG_FILE
VALIDATE $? "Enabling Backend"

systemctl restart backend       &>>$$LOG_FILE
VALIDATE $? "Re-starting backend"







