#!/bin/bash
R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

LOGS_FOLDER="/var/log/expense"
SCRIPT_NAME=$(echo $0 | cut -d "." -f1)
TIME_STAMP=$(date +%Y-%m-%d-%H-%M-%S)
LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME-$TIME_STAMP.log"

mkdir -p $LOGS_FOLDER

CHECK_ROOT(){
    USER_ID=$(id -u)
    if [ $USER_ID -ne 0 ]
    then
        echo -e "$R please run the script with root user access $N"        | tee -a $LOG_FILE
        exit 1
    fi
}
CHECK_ROOT

echo -e "Script started executing at :$Y $(date) $N"      | tee -a $LOG_FILE

VALIDATE(){
    if [ $1 -ne 0 ]
    then
        echo -e "$2 is $R FAILED.. $N"            | tee -a $LOG_FILE
        exit 1
    else
        echo -e "$2 is $G SUCCESS.. $N"           | tee -a $LOG_FILE
    fi
}

dnf install mysql-server -y             &>>$LOG_FILE        
VALIDATE $? "Installing Mysql-server"

systemctl enable mysqld                 &>>$LOG_FILE 
VALIDATE $? "Enabling mysql-server"

systemctl start mysqld                  &>>$LOG_FILE 
VALIDATE $? "Starting mysql-server"

mysql -h mysql.muntaj.fun -uroot -pExpenseApp@1 -e 'show databases;'    &>>$LOG_FILE 
if [ $? -ne 0 ]
then
    echo -e "$Y mysql root password $N is not setted..set it"     | tee -a $LOG_FILE
    mysql_secure_installation --set-root-pass ExpenseApp@1         &>>$LOG_FILE 
    VALIDATE $? "mysql root-pass set-up"
else
    echo -e "Mysql root password is $G already set skipp it $N"     | tee -a $LOG_FILE
fi



